### ISSUE TITLE
Should the predictor variables *really* be unique?

### ISSUE THREAD

**Issue by Ezibenroc** [DataDog/piecewise#5]
The code currently has this safety check:
https://github.com/DataDog/piecewise/blob/3a15a1c3113cbbecf979bb318f19f2c7fbdc9408/piecewise/regressor.py#L215-L216

This is a problem for me, as I have several occurences of each predictor variable.

I tried to remove this check and run the following code, where each predictor variable is repeated 10 times:
```python
import numpy
from piecewise.plotter import plot_data_with_regression
nbrep=10
t = numpy.concatenate([numpy.arange(10)]*nbrep)
v = numpy.array((
    [2*i for i in range(5)] +
    [10-i for i in range(5, 10)])*nbrep
) + numpy.random.normal(0, 1, 10*nbrep)
plot_data_with_regression(t, v)
```
It gives this result, which seems great to me:
![telechargement](https://user-images.githubusercontent.com/8900834/36552131-6cb97abe-17f9-11e8-9ec9-3fffcc17e494.png)

So, do you think that we could safely remove this safety check, or is there any corner case I didn't think of?

**Comment by StephenKappel** [comment]
Based on the way it's currently written, I believe it would be possible for different points at the same `t` to be modeled with two (or more) different linear segments. From a prediction perspective, this obviously makes no sense. However, it seems possible to prevent this problematic case by making the initialization a little smarter, so that it initializes all points with the same `t`s as modeled by the same linear segment. Since it does seem useful to handle this case, I'll take a pass at changing the initialization and creating a test to cover this case. PR to follow....

**Comment by StephenKappel** [comment]
@Ezibenroc - I've created a PR for this: https://github.com/DataDog/piecewise/pull/6

How does that look?

**Comment by StephenKappel** [comment]
I've merged the PR, so closing this issue. Feel free to follow-up if I missed anything.

**Comment by Ezibenroc** [comment]
It looks good, thank you!
